# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42cec3ccd9c322c8be3a943c1c61b20a9cfe466fcbd859e0dbe88c426659686f4cd9db7ac55626c41e15a36a319a6576b3e9861604b3d1e728fb7a91e4a73ad8

test:
  secret_key_base: 777451d3240b946d82a8ff6f3b7897d2925344ec913d23320bcabbb9bee44ea0f4ea1d821087e089e16b86d680043db72ca657e78705c64ad393ecb7197a6714

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
